const riskySystemOpenExtensions = new Set([
  "app",
  "application",
  "appimage",
  "appref-ms",
  "appx",
  "appxbundle",
  "bash",
  "bat",
  "cmd",
  "com",
  "command",
  "cpl",
  "csh",
  "deb",
  "desktop",
  "exe",
  "fish",
  "flatpak",
  "flatpakref",
  "flatpakrepo",
  "gadget",
  "hta",
  "jar",
  "jnlp",
  "js",
  "jse",
  "ksh",
  "lnk",
  "lua",
  "mpkg",
  "msi",
  "msc",
  "msp",
  "msix",
  "msixbundle",
  "php",
  "pif",
  "pl",
  "pkg",
  "ps1",
  "ps1xml",
  "ps2",
  "psc1",
  "psc2",
  "psd1",
  "psm1",
  "py",
  "pyw",
  "pyz",
  "pyzw",
  "rb",
  "reg",
  "rpm",
  "run",
  "scf",
  "scr",
  "sct",
  "sh",
  "snap",
  "tcl",
  "vbe",
  "vbs",
  "wsc",
  "wsf",
  "wsh",
  "wsb",
  "zsh",
]);

export function previewSystemOpenRequiresConfirmation(entryPath: string): boolean {
  const filename = entryPath
    .split(/[\\/]/)
    .at(-1)
    ?.trim()
    .replace(/[ .]+$/g, "")
    .toLocaleLowerCase("en-US") ?? "";
  const extensionStart = filename.lastIndexOf(".");
  if (extensionStart < 0 || extensionStart === filename.length - 1) return false;
  return riskySystemOpenExtensions.has(filename.slice(extensionStart + 1));
}
